import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Navbar from '../../Components/Navbar/Navbar';
import styles from '../../styles/projectdetail.module.scss';

const projectDetail = ({project}) => {
  return (
    <div className={styles.project}>
        <Head>
            <title>Project/{project.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

      <div className={styles.project_detail}>
        <Navbar />

        <div className={styles.project_detail_main}>
          <h1>{project.title}</h1>

          <Image src={project.images[0]} alt="website" width={700} height={500} />
        </div>
      </div>
    </div>
  )
}

export default projectDetail

export async function getStaticPaths() {
  const res = await axios.get('http://localhost:4000/api/projects/all')
  const datas = await res.data.message;

  const paths = datas.map((data) => ({
      params: {
        projectid: data._id
      }
  }))

  return {
    paths,
    fallback: true,
  }
}

export async function getStaticProps(context) {
  const params = context.params;

  const res = await axios.get(`http://localhost:4000/api/projects/${params.projectid}`)

  const project = await res.data.message;

  return {
    props: {
      project: project,
    }
  }
}