import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Navbar from '../../Components/Navbar/Navbar';
import styles from '../../styles/blogdetail.module.scss';

const blogDetail = ({blogDetail}) => {
  console.log(blogDetail);
  return (
    <div className={styles.blogdetail_page}>
      <Head>
            <title>Blogs/{blogDetail.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.project_detail}>
        <Navbar />

        <div className={styles.project_detail_main}>
          <h1>{blogDetail.title}</h1>
          <Image src={blogDetail.image} height={400} width={700} objectFit="cover" />
        </div>
        </div>
    </div>
  )
}

export default blogDetail

// getStaticPaths 
export async function getStaticPaths() {
  const res = await axios.get('http://localhost:4000/api/blogs/all');

  const data = await res.data.message;

  const paths = data.map((item) => {
    return {
      params: {
        blogid: item._id
      }
    }
  })

  return {
    paths,
    fallback: true
  }
}

// getStaticProps
export async function getStaticProps(context) {
  const params = context.params
  const res = await axios.get(`http://localhost:4000/api/blogs/${params.blogid}`)

  const data = await res.data.message;

  return {
    props: {
      blogDetail: data,
    }
  }
}