import Head from 'next/head';
import React from 'react';
import AboutMe from '../../Components/AboutMe/AboutMe';
import Contact from '../../Components/Contact/Contact';
import Footer from '../../Components/Footer/Footer';
import Navbar from '../../Components/Navbar/Navbar';
import Services from '../../Components/Services/Services';

import Skills from '../../Components/Skills/Skills';
import styles from '../../styles/about.module.scss';


const index = () => (
    <div className={styles.about}>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    <div className={styles.about_page}>
        <Navbar />
        <AboutMe pt="70px" social={true} />
        <Skills />
        {/*  */}
        <Services />
        <Contact />
        <Footer />
    </div>
    </div>
);

export default index;
